//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newss
    {
        public Newss()
        {
            this.Comments = new HashSet<Comment>();
            this.Reacts = new HashSet<React>();
            this.Totals = new HashSet<Total>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CtgrId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<React> Reacts { get; set; }
        public virtual ICollection<Total> Totals { get; set; }
    }
}
