//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Total
    {
        public int Id { get; set; }
        public int NewsId { get; set; }
        public int TotalLike { get; set; }
        public int TotalDislike { get; set; }
        public int TotalCmnt { get; set; }
    
        public virtual Newss Newss { get; set; }
    }
}
